
development:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  charset: utf8
  collation: utf8_bin
  database: sandbox_development

test:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  charset: utf8
  collation: utf8_bin
  database: sandbox_test

production:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  charset: utf8
  collation: utf8_bin
  database: sandbox_production
